title: Selina wei page
logo: /assets/img/photo.jpg
description: Welcome! This is Selina Wei's page! 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: Selina_w/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
